import { iSeller } from "./interfaces";

export const sellers: iSeller[] = [
  {
    seller_id: 1,
    name: "Edinho bolos",
    rating: 4.3,
    image_url:
      "https://img.freepik.com/free-vector/birthday-cake-icon-with-candles_204219-39.jpg?size=338&ext=jpg",
    category: "Bolos artesanais",
    distance: 20.4,
    address: "Rua dos Bobos, n° 0",
    opening_hours: "8 às 18h",
    products: [],
  },
  {
    seller_id: 2,
    name: "Nina docinhos",
    rating: 4.9,
    image_url: "https://image.flaticon.com/icons/png/128/1784/1784096.png",
    category: "Doces gourmet",
    distance: 10.4,
    address: "Rua dos Bobos, n° 0",
    opening_hours: "8 às 18h",
    products: [],
  },
  {
    seller_id: 3,
    name: "Indiano pizzas",
    rating: 4.7,
    image_url: "https://image.flaticon.com/icons/png/512/168/168307.png",
    category: "Pizzas",
    distance: 8.6,
    address: "Rua dos Bobos, n° 0",
    opening_hours: "8 às 18h",
    products: [],
  },
  {
    seller_id: 4,
    name: "Suzuya salgados",
    rating: 4.6,
    image_url: "https://image.flaticon.com/icons/png/512/859/859293.png",
    category: "Salgados",
    distance: 3.6,
    address: "Rua dos Bobos, n° 0",
    opening_hours: "8 às 18h",
    products: [],
  },
  {
    seller_id: 5,
    name: "Samurai bebidas",
    rating: 4.8,
    image_url:
      "https://img.flaticon.com/icons/png/512/1086/1086365.png?size=1200x630f&pad=10,10,10,10&ext=png&bg=FFFFFFFF",
    category: "Bebidas",
    distance: 9.1,
    address: "Rua dos Bobos, n° 0",
    opening_hours: "8 às 18h",
    products: [],
  },
];
